### ISSUE TITLE
import name 'trapz' from 'scipy.integrate' issue

### ISSUE THREAD

**Issue by lpathak97** [simone-mastrogiovanni/icarogw#17]
There is a bug related to importing icarogw. 

```
>>> import icarogw
Config not imported, automatically decides between Numpy and Cupy
Error in importing cupy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lalit.pathak/gwpop_cosmo_tifr/ligo_proj_1/icarogw-2.0.2/icarogw/__init__.py", line 1, in <module>
    from . import catalog
  File "/home/lalit.pathak/gwpop_cosmo_tifr/ligo_proj_1/icarogw-2.0.2/icarogw/catalog.py", line 2, in <module>
    from .conversions import radec2indeces, indices2radec, M2m, m2M
  File "/home/lalit.pathak/gwpop_cosmo_tifr/ligo_proj_1/icarogw-2.0.2/icarogw/conversions.py", line 2, in <module>
    import healpy as hp
  File "/home/lalit.pathak/.conda/envs/icarogw/lib/python3.10/site-packages/healpy/__init__.py", line 67, in <module>
    from .sphtfunc import (
  File "/home/lalit.pathak/.conda/envs/icarogw/lib/python3.10/site-packages/healpy/sphtfunc.py", line 27, in <module>
    from scipy.integrate import trapz
ImportError: cannot import name 'trapz' from 'scipy.integrate' (/home/lalit.pathak/.conda/envs/icarogw/lib/python3.10/site-packages/scipy/integrate/__init__.py)
>>> 

```

In the conda environments made with python version 3.10.14, it throws the above error. However, for conda environments made with python version 3.10.13, it doesn't show the error.  In the new versions of the scipy, the `trapz` has been renamed as `trapezoid` [see here](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.trapezoid.html).

**Comment by GregoirePierra** [comment]
Reason of the problem: healpy needs to import a version of scipy which has the trapz function in it. But the latest release of scipy change the name for this function, hence there is an incompatibility. 

Quick fix for this problem: Downgrade the version of scipy in the environment to scipy=1.10.1 and icarogw will be imported without problem.

**Comment by lalit-pathak** [comment]
Thanks @GregoirePierra
